In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
x=np.array([5,75,25,35,45,55]).reshape(-1,1)
y_=np.array([5,20,14,32,22,38])
model=LinearRegression()
model.fit(x,y_)
print(model.score(x,y_))
print(model.coef_)
print(model.intercept_)
print(model.predict(x))

0.3315606139262829
[0.28305085]
10.511299435028244
[11.92655367 31.74011299 17.58757062 20.4180791  23.24858757 26.07909605]


In [3]:
x_=np.arange(0,10,2).reshape(-1,1)
print(x_)
y_pred=model.predict(x_)
print(y_pred)

[[0]
 [2]
 [4]
 [6]
 [8]]
[10.51129944 11.07740113 11.64350282 12.20960452 12.77570621]
