In [1]:
list=[1,2,3,4]
list


[1, 2, 3, 4]

In [4]:
import numpy as np
array=np.array(list)
array

array([1, 2, 3, 4])

In [11]:
list1=[1,2,3]
list2=[3,45,5]
x=np.array(list1)
y=np.array(list2)
z=[]
def list_sum():
    z.append(x+y)
list_sum()
print(z)

[array([ 4, 47,  8])]


In [12]:
import numpy as np
array=[1,2,3,4]
array

[1, 2, 3, 4]

In [16]:
import numpy as np
array1=[1,2,3,4]
np.array(array1)

array([1, 2, 3, 4])

In [22]:
array=np.array([[1,2,3,4,5],[3,3,5,5,6]])
array

array([[1, 2, 3, 4, 5],
       [3, 3, 5, 5, 6]])

In [23]:
array.dtype


dtype('int32')

In [25]:
array.size

10

In [26]:
array.ndim


2

In [27]:
array.shape

(2, 5)

In [33]:
array=np.linspace(start=17,stop=31,num=50)
array

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [37]:
array1=[1,2,3]
array2=[0]
array3=[1]
array3[0]=array2[0]
array3[1:4]=array1[:]
print(array3)

[0, 1, 2, 3]
