In [50]:
from numpy import *

x=arange(24).reshape(4,3,2)
print(x)

print()

x=arange(2,11).reshape(3,3)
print(x)


x=arange(12,40)
print(x)

x=x[::-1]
print(x)

y=asfarray(x)
print(y)


n=5
x=arange(n*n).reshape(n,n)

print(x)
x[0:1,0:]=0
x[0:,0:1]=0
x[0:,n-1:]=0
x[n-1:,0:]=0

print(x)


x=zeros((8,8),dtype=int)
x[::2,1::2]=1
x[1::2,::2]=1
print(x)


x=[1,2,30]
x=append(x,[[40, 50,90], [70, 80, 90]])
print(x)

#intersection between 2 arrays

x=array([10,0, 20, 40, 60])
y=array([10,30,40])
print()
print(x)
print(y)

print("intersection: ",intersect1d(x,y))
print("Union: ",union1d(x,y))
x=array([10, 10, 20, 20, 30, 30,0,1])
print(unique(x))
x=tile(x,3)
print("repeating: ",x)


x=array([[10, 10, 20],[ 20, 30, 30],[0,1,2]],dtype=int32)
print(x)

n=7

e=x.flat[n-1]
print(x)
print(e)






















[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39]
[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12]
[39. 38. 37. 36. 35. 34. 33. 32. 31. 30. 29. 28. 27. 26. 25. 24. 23. 22.
 21. 20. 19. 18. 17. 16. 15. 14. 13. 12.]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  0  0  0  0]
 [ 0  6  7  8  0]
 [ 0 11 12 13  0]
 [ 0 16 17 18  0]
 [ 0  0  0  0  0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[ 1  2 30 40 50 90 70 80 90]

[10  0 20 40 60]
[10 30 40]
intersection:  [10 40]
Union:  [ 0 10 20 30 40 60]
[ 0  1 10 20 30]
repeating:  [10 10 20 20 30 30  0  1 10 10 20 20 30 30  0  1 10 10 20 20 30 30  0  1